[project]
name = "smaccl"
version = "1.0"
dependencies = [
    "numpy", 
    "xarray", 
    "pyopencl", 
    "h5py",
    "core @ git+https://github.com/hygeos/core.git",
    ]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pixi.tasks]
tests = "pytest tests/"

#[tool.pixi.pypi-dependencies]
#smaccl = { path = ".", editable = true }

[tool.pixi.dependencies]
pytest = "*"
numpy = "*"
xarray = "*"
pyopencl = "*"
pocl = "*"
h5py = "*"
scipy = "*"
netcdf4 = "*"
h5netcdf = "*"
dask = "*"
