[project]
name = "smaccl"
version = "1.0"
dependencies = [
    "numpy", 
    "xarray", 
    "pyopencl", 
    "h5py",
    "core @ git+https://github.com/hygeos/core.git"
    ]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.tasks]
tests = "pytest tests/"

[tool.pixi.dependencies]
pytest = "*"
numpy = "*"
xarray = "*"
pyopencl = "*"
pocl = "*"
h5py = "*"
scipy = "*"
netcdf4 = "*"
h5netcdf = "*"
dask = "*"

[tool.setuptools.packages.find]
where = ["smaccl"]
include = ["src_opencl"]

[tool.pixi.pypi-dependencies]
smaccl = { path = ".", editable = true }